---
ID: "0acbfea0-c6b1-4263-993f-5bcb231a1fff"
Parent: "c34e89d5-7f6c-4977-967b-2e5c886c27e0"
Template: "ab154d3d-1126-4ab4-ac21-8b86e6bd70ea"
Path: /sitecore/system/Modules/PowerShell/Script Library/SPE/Reporting/Content Reports/Reports/Configuration Audit
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: Office/32x32/clipboard_checks.png
- ID: "613d128b-7bf2-40f4-84cb-6717408f9806"
  Hint: ShowRule
  Type: Rules
  Value: |
    <ruleset>
      <rule
        uid="{6E35CAA6-FAAC-4571-A947-7A19C22011F4}"
        name="Admin or Maintainer">
        <conditions>
          <or
            uid="3010A5B7BEB34CD8977F6B3D7F00B23D">
            <or
              uid="4F33A6E0417E4EF380936ECDBFF900EC">
              <condition
                id="{33D5F360-CA8F-4193-AA5A-B52BEA2C84B4}"
                uid="2F780EF5CFBF4D87A7B2FFAC523A4417" />
              <condition
                id="{96C04ABA-A209-4BB5-AA37-73B5FDC7565E}"
                uid="70840624A49E48B999437C2B8D85ED4C"
                value="sitecore\Sitecore Client Maintaining" />
            </or>
            <condition
              id="{AAC2CC73-828C-4E42-9765-EA9E0B53390A}"
              uid="318CA49482CF4679A822497AD9F350E0" />
          </or>
        </conditions>
      </rule>
    </ruleset>
Languages:
- Language: da
  Fields:
  - ID: "9541e67d-ce8c-4225-803d-33f7f29f09ef"
    Hint: __Short description
    Value: Gennemse generelle detaljer om Sitecore løsningen.
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Konfigurationsrevision
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190718T152026Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "6711e65f-d2c3-41ef-8eac-76fb870c8104"
- Language: en
  Fields:
  - ID: "9541e67d-ce8c-4225-803d-33f7f29f09ef"
    Hint: __Short description
    Value: Review general details about the Sitecore solution.
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Configuration Audit
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20140413T182959Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "6ce0093a-2037-4598-84f4-55e54ddd20b8"
