---
ID: "69a36b24-46f9-43ff-a6ec-6c598f8371a0"
Parent: "6d82fcd8-c379-443c-97a9-c6423c71e7d5"
Template: "6d82fcd8-c379-443c-97a9-c6423c71e7d5"
Path: /sitecore/templates/Modules/PowerShell Console/PowerShell Script Module/__Standard Values
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: Software/32x32/jar_delete.png
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: |
    {AB154D3D-1126-4AB4-AC21-8B86E6BD70EA}
    {DD22F1B3-BD87-4DB2-9E7D-F7A496888D43}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20141101T105127
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
