---
ID: "8ac68939-310b-41f5-84cf-c817c8e5a34b"
Parent: "2fd18de6-d590-4ebb-9476-16446a4d6bf6"
Template: "6d1cd897-1936-4a3a-a511-289a94c2a7b1"
Path: /sitecore/system/Dictionary/PowerShell/P/Pick the settings for the module that you will be creating
DB: core
SharedFields:
- ID: "580c75a8-c01a-4580-83cb-987776ceb3af"
  Hint: Key
  Value: Pick the settings for the module that you will be creating and the integration points to include in it.
Languages:
- Language: da
  Fields:
  - ID: "2ba3454a-9a9c-4cdf-a9f8-107fd484eb6e"
    Hint: Phrase
    Value: Vælg opsætning for det modul du vil lave og integrationspunkter til inkludering i dette.
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190718T151816Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
- Language: en
  Fields:
  - ID: "2ba3454a-9a9c-4cdf-a9f8-107fd484eb6e"
    Hint: Phrase
    Value: Pick the settings for the module that you will be creating and the integration points to include in it.
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160826T102920
